import type { AmazonBatchDetailView, AmazonImportListItem } from "./server/ui-read-service";

export const amazonImportListFixtures: AmazonImportListItem[] = [
  {
    id: "batch-empty",
    period: "2026-07-05 - 2026-07-11",
    status: "uploaded",
    sourceFileCompleteness: "0/4",
    paymentReconciliationStatus: "not_started",
    fuelReconciliationStatus: "not_started",
    blockingIssueCount: 0,
    warningCount: 0,
    canonicalRevenueTotal: 0,
    projectedLoadCount: 0,
    projectedFuelExpenseCount: 0,
    candidateCount: 0,
    lastUpdated: "2026-07-12T12:00:00Z",
    creator: "Team member",
  },
  {
    id: "batch-ready-display",
    period: "2026-07-12 - 2026-07-18",
    status: "needs_review",
    sourceFileCompleteness: "4/4",
    paymentReconciliationStatus: "passed",
    fuelReconciliationStatus: "warning",
    blockingIssueCount: 3,
    warningCount: 5,
    canonicalRevenueTotal: 12500,
    projectedLoadCount: 8,
    projectedFuelExpenseCount: 12,
    candidateCount: 2,
    lastUpdated: "2026-07-19T12:00:00Z",
    creator: "Team member",
  },
];

export const amazonImportDetailFixtures: Record<string, AmazonBatchDetailView> = {
  empty: {
    id: "batch-empty",
    status: "uploaded",
    period: "2026-07-05 - 2026-07-11",
    notes: "Weekly import setup",
    role: "writer",
    archived: false,
    requiredFilesPresent: false,
    canMutate: true,
    canParse: false,
    files: [],
    workflow: [
      { key: "files", label: "Files", state: "in_progress", detail: "Upload required source files." },
      { key: "parsing", label: "Parsing", state: "not_started", detail: "Parsing has not completed." },
      { key: "reconciliation", label: "Reconciliation", state: "not_started", detail: "Financial checks are display-only." },
      { key: "matching", label: "Matching", state: "not_started", detail: "Payment and trip matching summary." },
      { key: "references", label: "References", state: "not_started", detail: "Read-only reference readiness." },
      { key: "projection", label: "Projection", state: "not_started", detail: "Projection summary only." },
      { key: "candidates", label: "Candidates", state: "not_started", detail: "Candidate summary only." },
      { key: "statements", label: "Statements", state: "not_started", detail: "Statement generation is not enabled in this slice." },
    ],
    reconciliation: {
      revenue: {},
      fuel: {},
    },
    issues: [],
    referenceReadiness: {
      revenue: { canonicalReady: 0, projectionReady: 0, settlementReady: 0, statementDisplayReady: 0 },
      fuel: { sourceReady: 0, expenseProjectionReady: 0, settlementDeductionReady: 0 },
      unresolved: { drivers: 0, vehicles: 0, facilities: 0, fuelAssignments: 0, teamRules: 0 },
    },
    projection: {
      revenue: { eligibleCanonicalItemCount: 0, prospectiveLoadCount: 0, grossAmount: 0, alreadyProjectedAmount: 0, unchangedCount: 0, conflictCount: 0, skippedCount: 0, notSettlementReadyCount: 0, previewRevision: "00000000" },
      fuel: { eligibleProductLineCount: 0, prospectiveExpenseCount: 0, amount: 0, placeholderSkips: 0, creditRefundIssues: 0, unchangedCount: 0, conflictCount: 0, notDeductionReadyCount: 0, previewRevision: "00000000" },
    },
    candidates: [],
    history: [],
  },
  warning: {
    id: "batch-warning",
    status: "needs_review",
    period: "2026-07-12 - 2026-07-18",
    notes: null,
    role: "viewer",
    archived: false,
    requiredFilesPresent: true,
    canMutate: false,
    canParse: false,
    files: [
      { id: "file-payment", sourceType: "amazon_payment", label: "Amazon Payment", sanitizedFilename: "PAYMENT.xlsx", verifiedSizeBytes: 120000, status: "parsed", parserName: "amazon-payment-xlsx", parserVersion: "0.1.0", schemaStatus: "compatible", warningCount: 1, blockingCount: 0, uploadedAt: "2026-07-19T12:00:00Z" },
      { id: "file-trips", sourceType: "amazon_trips", label: "Amazon Trips", sanitizedFilename: "Trips.csv", verifiedSizeBytes: 64000, status: "parsed", parserName: "amazon-trips-csv", parserVersion: "0.1.0", schemaStatus: "warning", warningCount: 4, blockingCount: 0, uploadedAt: "2026-07-19T12:00:00Z" },
      { id: "file-fuel", sourceType: "fuel_card", label: "Fuel Card Report", sanitizedFilename: "fuel.pdf", verifiedSizeBytes: 400000, status: "parsed", parserName: "octane-fuel-pdf", parserVersion: "0.1.0", schemaStatus: "warning", warningCount: 1, blockingCount: 0, uploadedAt: "2026-07-19T12:00:00Z" },
    ],
    workflow: [
      { key: "files", label: "Files", state: "completed", detail: "Required source files are present." },
      { key: "parsing", label: "Parsing", state: "completed", detail: "Required files parsed." },
      { key: "reconciliation", label: "Reconciliation", state: "needs_review", detail: "Warnings are present." },
      { key: "matching", label: "Matching", state: "completed", detail: "Payment and trip matching summary." },
      { key: "references", label: "References", state: "blocked", detail: "Read-only reference readiness." },
      { key: "projection", label: "Projection", state: "completed", detail: "Projection summary only." },
      { key: "candidates", label: "Candidates", state: "needs_review", detail: "Candidate summary only." },
      { key: "statements", label: "Statements", state: "not_started", detail: "Statement generation is not enabled in this slice." },
    ],
    reconciliation: {
      revenue: { summaryInvoiceTotal: 12500, validPaymentRowTotal: 12500, canonicalRevenueTotal: 12500, unassignedRevenue: 0, status: "passed", canonicalRevenueItemCount: 8, exact: 8, inferred: 0, ambiguous: 0, unmatched: 0 },
      fuel: { reportedTransactionCount: 30, realParsedTransactionCount: 29, productLineCount: 33, reportedAmount: 3000, calculatedAmount: 3000, quantityStatus: "passed", discountStatus: "passed", financialStatus: "passed", transactionCountStatus: "warning" },
    },
    issues: [
      { category: "facility", label: "Facility mapping", uniqueRootCount: 3, affectedDependencyCount: 5, severity: "blocking" },
      { category: "team_split", label: "Team split", uniqueRootCount: 1, affectedDependencyCount: 1, severity: "blocking" },
      { category: "parser", label: "Parser", uniqueRootCount: 5, affectedDependencyCount: 5, severity: "warning" },
    ],
    referenceReadiness: {
      revenue: { canonicalReady: 8, projectionReady: 8, settlementReady: 0, statementDisplayReady: 0 },
      fuel: { sourceReady: 3, expenseProjectionReady: 3, settlementDeductionReady: 0 },
      unresolved: { drivers: 2, vehicles: 1, facilities: 3, fuelAssignments: 2, teamRules: 1 },
    },
    projection: {
      revenue: { eligibleCanonicalItemCount: 8, prospectiveLoadCount: 8, grossAmount: 12500, alreadyProjectedAmount: 0, unchangedCount: 0, conflictCount: 0, skippedCount: 0, notSettlementReadyCount: 8, previewRevision: "abcd1234" },
      fuel: { eligibleProductLineCount: 12, prospectiveExpenseCount: 12, amount: 3000, placeholderSkips: 1, creditRefundIssues: 0, unchangedCount: 0, conflictCount: 0, notDeductionReadyCount: 12, previewRevision: "abcd5678" },
    },
    candidates: [
      {
        id: "candidate-1",
        statementType: "owner_operator",
        period: "2026-07-12 - 2026-07-18",
        payeeDisplay: "Payee",
        unitDisplay: "Unit A",
        selectedRevenueCount: 8,
        gross: 12500,
        selectedFuelAmount: 3000,
        totalDeductions: 3000,
        net: 9500,
        status: "needs_review",
        blockingIssueCount: 2,
        warningCount: 1,
        templateVersion: "amazon-statement-v1",
        calculationRevision: "amazon-candidate-rules-v1",
        previewRevision: "preview-1",
        approvedAt: null,
        lastCalculatedAt: "2026-07-19T12:00:00Z",
        settlementId: null,
      },
    ],
    history: [
      { action: "candidate_needs_review", actor: "-", time: "2026-07-19T12:00:00Z", result: "needs_review", reason: null },
    ],
  },
};

export const amazonReferenceReviewFixtures = {
  mixed: {
    batchId: "batch-ui",
    role: "writer",
    archived: false,
    canMutate: true,
    counts: {
      byCategory: {
        driver: 4,
        vehicle: 3,
        facility: 1,
        fuel_assignment: 6,
        team_split: 1,
      },
    },
    options: {
      people: [
        { id: "person-1", label: "Driver One", type: "company_driver", status: "active" },
        { id: "person-2", label: "Driver Two", type: "company_driver", status: "active" },
      ],
      vehicles: [
        { id: "vehicle-1", unitNumber: "100", description: "Truck", status: "active" },
        { id: "vehicle-2", unitNumber: "200", description: "Sleeper", status: "active" },
      ],
    },
    tasks: [
      { id: "task-1", category: "driver", issueCode: "unresolved_driver_identifier", severity: "blocking", provider: "amazon", identifierType: "driver_display_name", safeExternalDisplay: "Driver identifier", affectedRevenueItems: 8, affectedFuelGroups: 0, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["approve", "reject"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 8, fuelGroupsAffected: 0, readinessChanges: ["settlement readiness"], statementDisplayDependencies: 0, settlementDependencies: 8 }, placeholder: false, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 1 },
      { id: "task-2", category: "vehicle", issueCode: "unresolved_vehicle_identifier", severity: "blocking", provider: "amazon", identifierType: "tractor_vehicle_id", safeExternalDisplay: "UN...01", affectedRevenueItems: 4, affectedFuelGroups: 0, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["approve", "archive"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 4, fuelGroupsAffected: 0, readinessChanges: ["settlement readiness"], statementDisplayDependencies: 0, settlementDependencies: 4 }, placeholder: false, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 1 },
      { id: "task-3", category: "facility", issueCode: "unresolved_facility", severity: "blocking", provider: "amazon", identifierType: "facility_code", safeExternalDisplay: "FA...01", affectedRevenueItems: 5, affectedFuelGroups: 0, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["approve", "reject"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 5, fuelGroupsAffected: 0, readinessChanges: ["statement display readiness"], statementDisplayDependencies: 5, settlementDependencies: 0 }, placeholder: false, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 1 },
      { id: "task-4", category: "fuel_assignment", issueCode: "unmatched_fuel_assignment", severity: "blocking", provider: "octane", identifierType: "fuel_card", safeExternalDisplay: "Fuel card ending 0001", affectedRevenueItems: 0, affectedFuelGroups: 1, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["approve", "reject"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 0, fuelGroupsAffected: 1, readinessChanges: ["fuel settlement deduction readiness"], statementDisplayDependencies: 0, settlementDependencies: 1 }, placeholder: false, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 1 },
      { id: "task-5", category: "fuel_assignment", issueCode: "unmatched_fuel_assignment", severity: "warning", provider: "octane", identifierType: "fuel_card", safeExternalDisplay: "Fuel group 99", affectedRevenueItems: 0, affectedFuelGroups: 1, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["informational"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 0, fuelGroupsAffected: 1, readinessChanges: ["fuel settlement deduction readiness"], statementDisplayDependencies: 0, settlementDependencies: 1 }, placeholder: true, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 1 },
      { id: "task-6", category: "team_split", issueCode: "missing_team_split", severity: "blocking", provider: "amazon", identifierType: "team_key", safeExternalDisplay: "Team of 2 drivers", affectedRevenueItems: 1, affectedFuelGroups: 0, effectiveDateRange: "Requires reviewed effective dates", status: "open", availableActions: ["approve", "archive"], dependencySummaries: [], impactPreview: { revenueItemsAffected: 1, fuelGroupsAffected: 0, readinessChanges: ["settlement readiness"], statementDisplayDependencies: 0, settlementDependencies: 1 }, placeholder: false, financialBlocked: false, sourceRevision: "rev-1", teamMemberCount: 2 },
    ],
    history: [
      { id: "history-1", category: "driver", decisionType: "reject_external_driver_mapping", status: "rejected", reviewer: "Reviewer", decidedAt: "2026-07-19T12:00:00Z", effectiveFrom: "2026-07-01", effectiveTo: null, reason: "Not the correct internal person.", safeSummary: "Driver mapping decision", supersededOrArchived: false },
      { id: "history-2", category: "vehicle", decisionType: "archive_vehicle_alias_mapping", status: "archived", reviewer: "Reviewer", decidedAt: "2026-07-19T13:00:00Z", effectiveFrom: "2026-07-01", effectiveTo: "2026-07-10", reason: "Superseded by newer range.", safeSummary: "Vehicle alias decision", supersededOrArchived: true },
    ],
  },
  conflict: {
    batchId: "batch-ui",
    taskId: "task-1",
    error: "Reference task is no longer available. Refresh and try again.",
  },
};
