export const MAINTENANCE_TERMS = {
  addMaintenance: "Bakım Ekle",
  updateMileage: "Mileage Güncelle",
  startInspection: "Inspection Başlat",
  otherActions: "Diğer İşlemler",
  periodicMaintenance: "Periyodik Bakım",
  repair: "Tamir / Arıza",
  serviceType: "Bakım / Tamir Çeşidi",
  performedDate: "Yapılma Tarihi",
  performedMileage: "Yapıldığı Mileage",
  totalCost: "Toplam Maliyet",
  extraDetails: "Ek Detaylar",
  updateNextDue: "Sonraki bakımı güncelle",
  advancedPlanSettings: "Gelişmiş hatırlatıcı ayarları",
  maintenancePlans: "Bakım Hatırlatıcıları",
  lastDoneMaintenance: "Son Yapılan Bakım",
  mileageHistory: "Mileage Geçmişi",
  firstDueLimit: "İlk Dolan Sınır",
  plannedUnplanned: "Planlı / Plansız",
  insufficientMileage: "Mileage Verisi Yetersiz",
};

export function formatMaintenanceCategory(category: string): string {
  const labels: Record<string, string> = {
    preventive_maintenance: "Preventive Maintenance",
    engine: "Motor",
    fuel_system: "Fuel System",
    turbo_air_intake: "Turbo / Air Intake",
    aftertreatment: "Aftertreatment / DEF / DPF",
    transmission_clutch: "Transmission / Clutch",
    driveline_differential: "Driveline / Differential",
    cooling_system: "Cooling System",
    air_system: "Air System",
    brakes_wheel_end: "Brakes / Wheel End",
    suspension_steering: "Suspension / Steering",
    tires: "Tires",
    electrical: "Electrical",
    hvac_ac: "HVAC / A/C",
    apu: "APU",
    cab_body_glass: "Cab / Body / Glass",
    fifth_wheel_coupling: "Fifth Wheel / Coupling",
    trailer: "Trailer",
    dot_inspection: "DOT / Inspection",
    other: "Other",
    routine_pm: "Preventive Maintenance",
    transmission_driveline: "Transmission / Driveline",
    cooling: "Cooling System",
    road_service_towing: "Other",
    driver_damage: "Driver Damage",
    warranty_recovery: "Warranty Recovery",
  };
  return labels[category] ?? category.replace(/_/g, " ");
}
